import { Apartment } from './apartment';

export const APARTMENTS: Apartment[] = [
  { id: 11, 
    name: 'Mr. Nice', 
    description: "Very Good", 
    floorAreaSize: 10.1,
    pricePerMonth: 2000,
    numberOfRooms: 4,
    longitude: 10.1,
    latitude: 14.2,
    createdAt: '2016-08-11',
    realtorName: 'John Walker'
  },
  { id: 12, name: 'Narco', 
  description: "Very Good", 
  floorAreaSize: 10.1,
  pricePerMonth: 2000,
  numberOfRooms: 4,
  longitude: 10.1,
  latitude: 14.2,
  createdAt: '2016-08-11',
  realtorName: 'John Walker' },
  { id: 13, name: 'Bombasto', 
  description: "Very Good", 
  floorAreaSize: 10.1,
  pricePerMonth: 2000,
  numberOfRooms: 4,
  longitude: 10.1,
  latitude: 14.2,
  createdAt: '2016-08-11',
  realtorName: 'John Walker' },
  { id: 14, name: 'Celeritas', 
  description: "Very Good", 
  floorAreaSize: 10.1,
  pricePerMonth: 2000,
  numberOfRooms: 4,
  longitude: 10.1,
  latitude: 14.2,
  createdAt: '2016-08-11',
  realtorName: 'John Walker' }
];